[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vppcfg"
version = "0.0.1"
dependencies = [
    'requests',
    'importlib-metadata; python_version<"3.8"',
]

[project.scripts]
vppcfg = "vppcfg:vppcfg.main"

[options]
include_package_data = true